print("running data prep")
source("code/data_prep.R")

print("running figure_1.R")
source("code/figure_1.R")
print("running figure_2.R")
source("code/figure_2.R")
print("running figure_3.R")
source("code/figure_3.R")
print("running figure_4.R")
source("code/figure_4.R")
print("running figure_5.R")
source("code/figure_5.R")

print("running figure_S1.R")
source("code/figure_S1.R")
print("running figure_S2.R")
source("code/figure_S2.R")
print("running figure_S3.R")
source("code/figure_S3.R")
print("running figure_S4.R")
source("code/figure_S4.R")
print("running figure_S5.R")
source("code/figure_S5.R")
print("running figure_S6.R")
source("code/figure_S6.R")
print("running figure_S7.R")
source("code/figure_S7.R")
print("running figure_S8.R")
source("code/figure_S8.R")
print("running figure_S9.R")
source("code/figure_S9.R")
print("running figure_S10.R")
source("code/figure_S10.R")
print("running figure_S11.R")
source("code/figure_S11.R")
print("running figure_S12.R")
source("code/figure_S12.R")
print("running figure_S13.R")
source("code/figure_S13.R")

print("running table_S1.R")
source("code/table_S1.R")
print("running table_S2.R")
source("code/table_S2.R")
print("running table_S3.R")
source("code/table_S3.R")
print("running table_S4.R")
source("code/table_S4.R")
print("running table_S5.R")
source("code/table_S5.R")
print("running table_S6.R")
source("code/table_S6.R")
print("running table_S7.R")
source("code/table_S7.R")
